### ISSUE TITLE
Log invalid tokens in API requests

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#346]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/177811481)    

    If a token from a different (eduID) IdP is used the logging shows :
```
2021-04-19 08:58:59,412 ERROR [http-nio-9189-exec-4] myconext.api.DefaultErrorController:59 - Error occurred
myconext.exceptions.UserNotFoundException: null
	at java.util.Optional.orElseThrow(Optional.java:290)
	at myconext.eduid.APIController.eppn(APIController.java:34)
	at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
```
It would be useful to show the ID of the user

**Comment by phavekes** [comment]
https://github.com/OpenConext/OpenConext-myconext/commit/36b7d1460013f03c6ef0750aec4f089873875ad4 (Okke Harsta - Apr 29, 2021)
