### ISSUE TITLE
Error after incomplete app enrollment

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#370]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/182397572)    

    I\'ve started the app-enrollment, but stopped before registering a recovery method. 

Now, all actions in mijn.eduid result in a 404 message, and the error logs showing a database error:
```
2022-06-07 08:32:48,623 ERROR [http-nio-9189-exec-2] myconext.api.DefaultErrorController:56 - Error occurred
org.springframework.dao.IncorrectResultSizeDataAccessException: Query { "$java" : Query: { "userId" : "5f563886be53463668fbc324"}, Fields: {}, Sort: {} } returned non unique result.
	at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.oneValue(ExecutableFindOperationSupport.java:139)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.lambda$getExecution$4(AbstractMongoQuery.java:159)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.doExecute(AbstractMongoQuery.java:132)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:107)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:159)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy115.findRegistrationByUserId(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy115.findRegistrationByUserId(Unknown Source)
	at myconext.api.UserController.userResponseRememberMe(UserController.java:508)
	at myconext.api.UserController.me(UserController.java:252)

```

**Comment by phavekes** [comment]
Logs of enrolment atempt:
```
2022-06-07 08:22:24,177  INFO [http-nio-9189-exec-9] myconext.oidcng.OpenIDConnectRemote:50 - Start fetching tokens from oidc-ng for peter+test2_2@havekes.eu
2022-06-07 08:22:24,300  INFO [http-nio-9189-exec-9] myconext.oidcng.OpenIDConnectRemote:60 - Tokens result from oidc-ng []
2022-06-07 08:22:30,148  INFO [http-nio-9189-exec-1] myconext.tiqr.TiqrController:147 - Started enrollment for peter+test2_2@havekes.eu
2022-06-07 08:22:30,257 DEBUG [http-nio-9189-exec-4] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:31,378 DEBUG [http-nio-9189-exec-3] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:32,495 DEBUG [http-nio-9189-exec-7] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:33,629 DEBUG [http-nio-9189-exec-8] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:34,769 DEBUG [http-nio-9189-exec-9] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:35,897 DEBUG [http-nio-9189-exec-10] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:37,012 DEBUG [http-nio-9189-exec-2] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:38,414 DEBUG [http-nio-9189-exec-1] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:39,865 DEBUG [http-nio-9189-exec-4] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:41,011 DEBUG [http-nio-9189-exec-6] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:42,172 DEBUG [http-nio-9189-exec-7] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:43,374 DEBUG [http-nio-9189-exec-8] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:44,487 DEBUG [http-nio-9189-exec-9] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:45,617 DEBUG [http-nio-9189-exec-10] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:48,777 DEBUG [http-nio-9189-exec-4] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:49,875 DEBUG [http-nio-9189-exec-3] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:50,975 DEBUG [http-nio-9189-exec-5] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:52,212 DEBUG [http-nio-9189-exec-6] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:53,324 DEBUG [http-nio-9189-exec-7] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:54,569 DEBUG [http-nio-9189-exec-8] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:55,695 DEBUG [http-nio-9189-exec-9] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:22:56,115  INFO [http-nio-9189-exec-10] myconext.tiqr.TiqrController:156 - Returning metaData for Peter-Test2 Havekes-Test2
2022-06-07 08:22:56,803 DEBUG [http-nio-9189-exec-4] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:22:57,905 DEBUG [http-nio-9189-exec-3] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:22:58,980 DEBUG [http-nio-9189-exec-5] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:23:00,105 DEBUG [http-nio-9189-exec-6] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:23:01,302 DEBUG [http-nio-9189-exec-7] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:23:02,399 DEBUG [http-nio-9189-exec-8] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:23:03,674 DEBUG [http-nio-9189-exec-10] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status PROCESSED
2022-06-07 08:23:41,157  INFO [http-nio-9189-exec-8] myconext.tiqr.TiqrController:147 - Started enrollment for peter+test2_2@havekes.eu
2022-06-07 08:23:41,590 DEBUG [http-nio-9189-exec-7] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:23:42,712 DEBUG [http-nio-9189-exec-5] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status INITIALIZED
2022-06-07 08:23:43,730  INFO [http-nio-9189-exec-6] myconext.tiqr.TiqrController:156 - Returning metaData for Peter-Test2 Havekes-Test2
2022-06-07 08:23:44,901 DEBUG [http-nio-9189-exec-2] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:23:46,295 DEBUG [http-nio-9189-exec-4] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:23:47,459 DEBUG [http-nio-9189-exec-1] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:23:48,690 DEBUG [http-nio-9189-exec-3] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:23:49,920 DEBUG [http-nio-9189-exec-8] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:23:52,169 DEBUG [http-nio-9189-exec-7] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status RETRIEVED
2022-06-07 08:23:54,414 DEBUG [http-nio-9189-exec-10] myconext.tiqr.TiqrController:165 - Polling enrollment for Peter-Test2 Havekes-Test2 with status PROCESSED
2022-06-07 08:23:54,600  INFO [scheduling-1] m.manage.ManageServiceProviderResolver:52 - Starting to refresh metadata for entityID: Optional.empty from https://manage.test2.surfconext.nl
2022-06-07 08:23:54,644  INFO [scheduling-1] m.manage.ManageServiceProviderResolver:61 - Refreshed 79 Service providers, 43 Relying parties and 20 Resource servers in 44 ms
2022-06-07 08:25:19,955 ERROR [http-nio-9189-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]:175 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Enrollment can only be called when the status is RETRIEVED. Current status is PROCESSED] with root cause
java.lang.IllegalArgumentException: Enrollment can only be called when the status is RETRIEVED. Current status is PROCESSED
	at tiqr.org.DefaultTiqrService.enrollData(DefaultTiqrService.java:77)
	at myconext.tiqr.TiqrController.doEnrollment(TiqrController.java:354)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
``` (Peter Havekes - Jun 7, 2022)
