### ISSUE TITLE
clean up incomplete tiqr-registrations

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#438]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/184778869)    

    If a user stops the process of enrolling a tiqr key before completing the recovery setup, he can not start a new registration, or use the tiqr-secret for authentication. These incomplete registrations should be removed automatically, or be detected so a new registration can be started.

**Comment by phavekes** [comment]
Steps to reproduce:
- Create a new eduID account and confirm email
- enroll app when asked
- complete registration in app
- close all browsers when asked to select recovery method
- login in a  mijn in a new browser window
- try to add an app -registration
Screen will show a spinner, no QR code

log will show 
```
2023-03-23 16:32:59,899 ERROR [http-nio-9189-exec-2] myconext.api.DefaultErrorController:60 - Error occurred; myconext.exceptions.ForbiddenException: Can not start enrollment when there is an existing Registration
myconext.exceptions.ForbiddenException: Can not start enrollment when there is an existing Registration
	at myconext.tiqr.TiqrController.doStartEnrollmentForUser(TiqrController.java:152)
	at myconext.tiqr.TiqrController.startEnrollment(TiqrController.java:123)
	at jdk.internal.reflect.GeneratedMethodAccessor346.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:156)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:327)
	at myconext.log.MDCFilter.doFilterInternal(MDCFilter.java:41)
```


 (Peter Havekes - Mar 23, 2023)

**Comment by phavekes** [comment]
Deployed new SNAPSHOT to build server. https://build.openconext.org/repository/public/snapshots/org/openconext/myconext-server/7.0.12-SNAPSHOT/myconext-server-7.0.12-20230327.081103-16.jar  (Okke Harsta - Mar 27, 2023)
