### ISSUE TITLE
Inform users if there is a pending Tiqr registration

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#447]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/185312740)    

    If a user starts a tiqr registration when one is already pending or completed, the web-ui only shows a spinner. The server-logs show:
```
2023-06-01 11:58:21,939 ERROR [http-nio-9189-exec-2] myconext.api.DefaultErrorController:60 - Error occurred; myconext.exceptions.ForbiddenException: Can not start enrollment when there is an existing Registration
myconext.exceptions.ForbiddenException: Can not start enrollment when there is an existing Registration
	at myconext.tiqr.TiqrController.doStartEnrollmentForUser(TiqrController.java:152)
	at myconext.tiqr.TiqrController.startEnrollment(TiqrController.java:123)
	at jdk.internal.reflect.GeneratedMethodAccessor327.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

Inform the user in the web-ui there already is an (pending) registration

**Comment by phavekes** [comment]
(Okke Harsta - Jul 11, 2023)

**Comment by phavekes** [comment]
(Okke Harsta - Jul 11, 2023)
